window.HHVC_PAGES = window.HHVC_PAGES || {}
window.HHVC_DATA = {
  pages: window.HHVC_PAGES,
  order: [
    ['pestsTopic', 'Topic: Pests and housing problems'],
    ['ratsReport', 'Transaction: Report rats or mice'],
    ['cockroachesReport', 'Transaction: Report cockroaches'],
    ['bedBugsReport', 'Transaction: Report bed bugs'],
    ['bedBugsInfo', 'Information: Bed bug rules and prevention'],
    ['mosquitoesReport', 'Transaction: Report mosquitoes'],
    ['pigeonsReport', 'Transaction: Report pigeons'],
    ['garbageReport', 'Transaction: Report garbage or clutter'],
    ['vegetationReport', 'Transaction: Report overgrown vegetation'],
    ['moldReport', 'Transaction: Report mold from humidity or condensation'],
    ['payFee', 'Transaction: Pay your Healthy Housing fee'],
    ['scopeInfo', 'Information: Learn what HHVC can inspect'],
    ['ownerGuidance', 'Information: Integrated pest management for property managers'],
    ['afterReport', 'Information: What happens after you report'],
    ['tenantRights', 'Information: Tenant rights and reporting'],
    ['ratsPrevent', 'Information: Keep rats and mice out'],
    ['cockroachesPrevent', 'Information: Prevent cockroaches'],
    ['mosquitoesPrevent', 'Information: Prevent mosquitoes'],
    ['reduceMoisture', 'Information: Reduce indoor moisture, condensation, and humidity'],
  ],
}
