window.HHVC_PAGES = window.HHVC_PAGES || {}
window.HHVC_DATA = {
  pages: window.HHVC_PAGES,
  order: [
    ['pestsTopic', 'Topic page: Pests and housing problems'],
    ['reportHub', 'Resource collection: Report a problem'],
    ['preventHub', 'Resource collection: Prevent problems'],
    ['recordsHub', 'Resource collection: Look up building records'],
    ['findRecords', 'Transaction: Find complaints and inspection records'],
    ['findViolations', 'Transaction: Look up residential health code violations'],
    ['findHotelRecords', 'Transaction: Find residential hotel and shelter records'],
    ['findInspector', 'Information: Find your district inspector'],
    ['publicRecords', 'Transaction: Make a public records request'],
    ['ownerHub', 'Resource collection: Property owner responsibilities'],
    ['feeSchedule', 'Resource collection: Healthy Housing fee schedule FY27'],
    ['feeReport', 'Report: Healthy Housing fee schedule FY27'],
    ['ownerForms', 'Resource collection: Owner forms and IPM templates'],
    ['vectorRules', 'Resource collection: Director’s Rules for Vector Control'],
    ['noticeOfViolation', 'Step-by-step: Respond to a notice of violation'],
    ['ratsReport', 'Transaction: Report rats or mice'],
    ['cockroachesReport', 'Transaction: Report cockroaches'],
    ['bedBugsReport', 'Transaction: Report bed bugs'],
    ['bedBugsInfo', 'Information: Bed bug rules and prevention'],
    ['bedBugForms', 'Resource collection: Bed bug forms and guides'],
    ['mosquitoesReport', 'Transaction: Report mosquitoes'],
    ['wnvBirdReport', 'Transaction: Report a dead bird'],
    ['pigeonsReport', 'Transaction: Report pigeons'],
    ['garbageReport', 'Transaction: Report garbage or clutter'],
    ['vegetationReport', 'Transaction: Report overgrown vegetation'],
    ['moldReport', 'Transaction: Report mold from humidity or condensation'],
    ['payFee', 'Transaction: Pay your Healthy Housing fee'],
    ['scopeInfo', 'Information: Learn what HHVC can inspect'],
    ['ownerGuidance', 'Information: Integrated pest management for property owners and managers'],
    ['afterReport', 'Step-by-step: What happens after you report'],
    ['tenantRights', 'Information: Tenant rights and reporting'],
    ['ratsPrevent', 'Information: Keep rats and mice out'],
    ['cockroachesPrevent', 'Information: Prevent cockroaches'],
    ['mosquitoesPrevent', 'Information: Prevent mosquitoes'],
    ['vegetationInfo', 'Information: Prevent overgrown vegetation'],
    ['garbageInfo', 'Information: Prevent garbage and clutter problems'],
    ['mosquitoControl', 'Information: Mosquito Control Program'],
    ['mosquitoWorkshop', 'Campaign: Free mosquito education workshop'],
    ['raccoonInfo', 'Information: Raccoons and housing health'],
    ['raccoonLatrineCleanup', 'Step-by-step: Clean up a raccoon latrine safely'],
    ['pigeonInfo', 'Information: Pigeons and housing health'],
    ['miteInfo', 'Information: Mites and housing health'],
    ['miteTreatmentSteps', 'Step-by-step: Treat mite sources before rodenticides'],
    ['waspInfo', 'Information: Ground wasps and housing health'],
    ['flyInfo', 'Information: Flies and housing health'],
    ['reduceMoisture', 'Information: Reduce indoor moisture, condensation, and humidity'],
  ],
}
