window.HHVC_PAGES = window.HHVC_PAGES || {}
window.HHVC_DATA = {
  pages: window.HHVC_PAGES,
  order: [
    ['pestsTopic', 'Topic: Pests and housing problems'],
    ['recordsHub', 'Resource collection: Look up building records'],
    ['findRecords', 'Transaction: Find complaints and inspection records'],
    ['findViolations', 'Transaction: Look up residential health code violations'],
    ['findHotelRecords', 'Transaction: Find residential hotel and shelter records'],
    ['findInspector', 'Information: Find your district inspector'],
    ['publicRecords', 'Transaction: Make a public records request'],
    ['ownerHub', 'Resource collection: Property owner responsibilities'],
    ['noticeOfViolation', 'Information: How to respond to a notice of violation'],
    ['ratsReport', 'Transaction: Report rats or mice'],
    ['cockroachesReport', 'Transaction: Report cockroaches'],
    ['bedBugsReport', 'Transaction: Report bed bugs'],
    ['bedBugsInfo', 'Information: Bed bug rules and prevention'],
    ['mosquitoesReport', 'Transaction: Report mosquitoes'],
    ['wnvBirdReport', 'Transaction: Report a dead bird'],
    ['vegetationReport', 'Transaction: Report vegetation or garbage'],
    ['moldReport', 'Transaction: Report mold from humidity or condensation'],
    ['payFee', 'Transaction: Pay your Healthy Housing fee'],
    ['scopeInfo', 'Information: Learn what HHVC can inspect'],
    ['ownerGuidance', 'Information: Integrated pest management for property owners and managers'],
    ['afterReport', 'Information: What happens after you report'],
    ['tenantRights', 'Information: Tenant rights and reporting'],
    ['ratsPrevent', 'Information: Keep rats and mice out'],
    ['cockroachesPrevent', 'Information: Prevent cockroaches'],
    ['mosquitoesPrevent', 'Information: Prevent mosquitoes'],
    ['mosquitoControl', 'Information: Mosquito Control Program'],
    ['mosquitoWorkshop', 'Information: Free mosquito education workshop'],
    ['raccoonInfo', 'Information: Raccoons and housing health'],
    ['pigeonInfo', 'Information: Pigeons and housing health'],
    ['miteInfo', 'Information: Mites and housing health'],
    ['reduceMoisture', 'Information: Reduce indoor moisture, condensation, and humidity'],
  ],
}
